### ISSUE TITLE
Pages to App Router Migration

### ISSUE THREAD

**Issue by impurity-dev** [BabylonJS/Documentation#1021]
The documentation should be migrated from the pages router to the app router to take advantage of current and future NextJS features.

https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration

**Comment by RaananW** [comment]
i'm all for it, as long as we stay backwards compatible with the current URL structure

**Comment by impurity-dev** [comment]
> i'm all for it, as long as we stay backwards compatible with the current URL structure

Understood. I think the plus side is NextJS does offer an incremental migration, so Ill fool around with it this week and see what that would look like.

**Comment by RaananW** [comment]
Hey! i know it has been some time, any update on this? otherwise we will close it for now.

**Comment by impurity-dev** [comment]
@RaananW unfortunately I have been very bogged down with life :/ I'd close this for now!

**Comment by RaananW** [comment]
I'm totally with you 😀
Life happens...
