### ISSUE TITLE
Syntax errors in "The Very First Step" chapter of the Documentation for the ImportMesh method

### ISSUE THREAD

**Issue by frazard99** [BabylonJS/Documentation#1127]
In the part where the `ImportMesh` method is shown for the first time, the two JavaScript lines in the screenshot below have an ending semicolon, which leads to a syntax error if these lines are copied with the copy button. These semicolons must be removed.
![image](https://github.com/BabylonJS/Babylon.js/assets/62503177/273025dc-a08b-4b25-b2ee-9eb54f665ede)

**Comment by deltakosh** [comment]
cc @PatrickRyanMS

**Comment by PatrickRyanMS** [comment]
fixed https://github.com/BabylonJS/Documentation/pull/1128
