### ISSUE TITLE
.html example pages are not deployed correctly

### ISSUE THREAD

**Issue by VicenteCartas** [BabylonJS/Documentation#1166]
For some reason, any link that is related to an html example page (page1.html, page2.html...) doesn't work correctly.
![image](https://github.com/BabylonJS/Documentation/assets/1724160/96529a58-a199-4b69-a04a-b514c1bb3e4a)

But when running the documentation repo locally, it does actually work:
![image](https://github.com/BabylonJS/Documentation/assets/1724160/81cf0515-4ad3-477a-ac28-179b6ded801a)

The URL is slightly different, locally it has the .html at the end. The issue seems related to vercel.json:

{ "source": "/webpages/page1.html", "destination": "/webpages/page1" },

**Comment by RaananW** [comment]
Thanks for reporting! I'll look into that
