### ISSUE TITLE
Playground #KDPAQ9#16 is out of date with the tutorial text

### ISSUE THREAD

**Issue by VicenteCartas** [BabylonJS/Documentation#1171]
In the page: https://doc.babylonjs.com/features/introductionToFeatures/chap3/caranimation

The description says:

"In a similar way to how we animated the wheels we now animate the car to travel a straight line over 5 secs., stop for 2 secs. and then repeat."

And the JS code in the box shows the right animation keys and value to scene.beginAnimation, but on the playground:

https://playground.babylonjs.com/#KDPAQ9#16

The last key is missing:

carKeys.push({
    frame: 210,
    value: 4
});

And then scene.beginAnimation has to be updated accordingly in line 33:

scene.beginAnimation(car, 0, 210, true);

I tried to find the playgrounds, but I couldn't find them in the doc repo, if you point me to how to update them, I can do the change myself.

**Comment by RaananW** [comment]
The source has these lines:

![image](https://github.com/user-attachments/assets/bb072c15-51bd-4b4c-98ce-e29a19c295a1)

Which you can't see on github .md viewer, since they are custom markdown/html tags. This is how you update playgrounds

**Comment by VicenteCartas** [comment]
Fixed by #1170
