### ISSUE TITLE
Contributing Documentation page has broken images

### ISSUE THREAD

**Issue by richardtallent** [BabylonJS/Documentation#118]
This page has a number of image links to files that don't exist:

https://github.com/BabylonJS/Documentation/blob/master/content/How_To/contribute/contribute_to_documentation.md

There is a folder here with similar images -- perhaps a recent patch to add the "easy button" instructions for updating markdown files on GitHub didn't include some replacement images?

https://github.com/BabylonJS/Documentation/tree/master/public/img/contribute

**Comment by sebavan** [comment]
The links are correct but the template is failing as it apply a 0 * 0 size to the container :-( 

@RaananW or @deltakosh  might be able to fix that in no time as soon as they are back from vacations.

**Comment by RaananW** [comment]
I'll take care of this as soon as I'm on my desktop
