### ISSUE TITLE
Ability to remove a TOC from a page / to limit the levels

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#12]
Maybe some pages don't need a TOC? Like the What's new page.

Or maybe the What's new page needs a TOC but limited to the first level, which would be the version of the engine. Else, the TOC could be very long (see again the What's new page).

So, a mechanism that would allow to tag a page as having a TOC limited to the n first levels could be handy (use n = 0 to remove the TOC).

**Comment by RaananW** [comment]
The markdown has a metadata configurator written in YAML.

Adding

```yaml
toc-levels: NUMBER
```

will limit the ToC depth, 0 will remove it completely.
