### ISSUE TITLE
looks like link is not working in the shader documentation

### ISSUE THREAD

**Issue by Imaver** [BabylonJS/Documentation#1200]
Hi! Really enjoy working with BabylonJS and going trough the documentation, found that here the link returns 404, not sure what the right link should be tagging this, hopefully this could be helpful
https://github.com/BabylonJS/Extensions/tree/master/ShaderBuilder

https://github.com/BabylonJS/Documentation/blob/ce6cffaf0e7d7d04ed0535cbe6ae84ce96f5beb9/content/features/featuresDeepDive/materials/shaders/introToShaders.md?plain=1#L170

**Comment by RaananW** [comment]
thank you so much. the shaderbuilder was based on old code and was removed from the extensions repository. I will remove it from the docs.
