### ISSUE TITLE
Motor Joints Omitted from Constraints Deep Dive

### ISSUE THREAD

**Issue by Rex-tr909** [BabylonJS/Documentation#1217]
No information or examples regarding setting motors on 6dof or spring joints in physicsV2 deep dive. 

I have a nice clean example showing how to use motors here [Motor Joint Example](https://www.babylonjs-playground.com/#5KKGOT). Happy to PR this if it's suitable!

**Comment by sebavan** [comment]
I love it, it would be great, thanks :-)

**Comment by sebavan** [comment]
@CedricGuillemet can you check the example ?

**Comment by CedricGuillemet** [comment]
This is a great example @Rex-tr909 can't wait to see the PR! :)

**Comment by Rex-tr909** [comment]
#1218
