### ISSUE TITLE
Add TypeScript version of Getting Started

### ISSUE THREAD

**Issue by Odonno** [BabylonJS/Documentation#127]
I think it could be great to have also the TypeScript version of the `Getting Started` bootstrap code.

```
/// <reference path="babylon.2.2.d.ts" />

window.addEventListener('DOMContentLoaded', function() {
	let canvas = <HTMLCanvasElement>document.getElementById('renderCanvas');
	let engine = new BABYLON.Engine(canvas, true);

	let createScene = function() {
		// create a basic BJS Scene object
		let scene = new BABYLON.Scene(engine);
			
		// create a FreeCamera, and set its position to (x:0, y:5, z:-10)
		let camera = new BABYLON.FreeCamera('camera1', new BABYLON.Vector3(0, 5, -10), scene);
			
		// target the camera to scene origin
		camera.setTarget(BABYLON.Vector3.Zero());
			
		// attach the camera to the canvas
		camera.attachControl(canvas, false);
			
		// create a basic light, aiming 0,1,0 - meaning, to the sky
		let light = new BABYLON.HemisphericLight('light1', new BABYLON.Vector3(0, 1, 0), scene);
			
		// create a built-in "sphere" shape; its constructor takes 5 params: name, width, depth, subdivisions, scene
		let sphere = BABYLON.Mesh.CreateSphere('sphere1', 16, 2, scene);
			
		// move the sphere upward 1/2 of its height
		sphere.position.y = 1;
		
		// create a built-in "ground" shape; its constructor takes the same 5 params as the sphere's one
		let ground = BABYLON.Mesh.CreateGround('ground1', 6, 6, 2, scene);
			
		// return the created scene
		return scene;
	};

	let scene = createScene();

	engine.runRenderLoop(function() {
		scene.render();
	});

	window.addEventListener('resize', function() {
		engine.resize();
	});
});
```

**Comment by deltakosh** [comment]
That's a great idea! feel free to send a PR with this update

**Comment by Odonno** [comment]
Ok, good !
I'll do it asap.

**Comment by Odonno** [comment]
@deltakosh I spent some time to understand the code. I have some questions.

1. I need to update the *.jade files, am I right ?
2. To see changes, I need to make `grunt build` and `grunt serve` but it seems it rewrite many files. Is it normal ? indeed, there is many files in the staging.
3. About the home page, I would like to make a switch button (JavaScript | TypeScript). What do you think ? What's the best way to do this, include js script inside the page ?

Thanks.

**Comment by Temechon** [comment]
Hello! 
1. You have to update the jade file indeed (views/index.jade', and it will be compiled into HTML.
2. 'grunt build' will build all the documentation, it's a little bit overkill for your use. You can just use : grunt execute:compileIndex': it will compile only the index page. grunt serve will run the express server.
3. It's a very good idea! You can include a js script into the page (at the end of index.jade would be perfect).
Thank you for your contribution :)

**Comment by Odonno** [comment]
@Temechon Nice, it helps a lot.

**Comment by Temechon** [comment]
PR created, issue closed.
