### ISSUE TITLE
Wrong playground link in documentation

### ISSUE THREAD

**Issue by Awe1alex** [BabylonJS/Documentation#152]
on page https://doc.babylonjs.com/start/chap2/copies
which is "Getting Started - Chapter 2 - Making Copies"

"Expanding the House Building Function" example leads to Example from "Getting Started - Chapter 2 - Combining Meshes"  ""Combining Meshes In Your Scene" https://playground.babylonjs.com/#KBS9I5#75

**Comment by kihonkai** [comment]
It looks like the expected playground exists here: https://playground.babylonjs.com/#KBS9I5#77

**Comment by PirateJC** [comment]
Awesome thank you! Making this change now!

**Comment by PirateJC** [comment]
This was fixed back in Feb. Closing.
