### ISSUE TITLE
Babylon 101 Video Tutorial Series

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Documentation#154]
@thomlucc commented on [Mon May 18 2020](https://github.com/BabylonJS/OldDocumentationSite/issues/1955)

From [#6509](https://github.com/babylonjs/babylon.js/issues/6509) in Babylon.js repo

Create a series of tutorial/walkthrough videos to accompany the Babylon101 documentation. 
 These videos will help walk folks who are new to Babylon, through the beginning basics of how to use it.

- [ ] Intro and About the Course
- [ ] First Steps
- [ ] Discovering the Basics
- [ ] Parametric Shapes
- [ ] Position and Rotation
- [ ] Materials
- [ ] Cameras
- [ ] Lights
- [ ] Animation
- [ ] Cameras, Mesh Collisions and Gravity
- [ ] Intersect Collisions - mesh
- [ ] Picking Collisions
- [ ] Raycasting
- [ ] Sprites
- [ ] Particles
- [ ] Environment
- [ ] Height Map
- [ ] Shadows

**Comment by thomlucc** [comment]
Perhaps map the Babylon 101 series to the new Getting Started series

**Comment by PirateJC** [comment]
Closing this issue as it's not something that's widely asked for. We can revisit the idea in the future if the community would find the idea helpful.
