### ISSUE TITLE
Add a note about how to control glow layer with NME

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Documentation#155]
@deltakosh commented on [Thu Feb 20 2020](https://github.com/BabylonJS/OldDocumentationSite/issues/1896)

**Comment by thomlucc** [comment]
@PirateJC reference [this video](https://youtu.be/5ZuM-WLqEPQ) please and some comments. thx

**Comment by PirateJC** [comment]
Done.

https://github.com/BabylonJS/Documentation/pull/397

Added a new sub section for using the glow layer with a Node Material.

Included a small overview, the playground example from @PatrickRyanMS's video and the video itself.
