### ISSUE TITLE
NME: document and explain expected range of "distance" on the Replace Color node

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Documentation#157]
@thomlucc commented on [Wed Feb 19 2020](https://github.com/BabylonJS/OldDocumentationSite/issues/1889)

Question: What is the expected range of "distance" on the Replace Color node? It seems as though a value of 1.0 does not cover the whole range of possible replacement color values. I'm finding around 1.22-1.24 is needed to completely replace all tones of color, or is this just an isolated instance based on what colors I'm using (black to blue to white replacing blue with green pushing the range to replace black and white as well) 

answer: The distance is the distance between the two colors (as in len(a - b)) so it depends on the colors.

![image.png](https://images.zenhubusercontent.com/5dae4b4d14fb1000015c0e1e/7e463d67-f369-4468-af8a-9c792df800e5)

**Comment by thomlucc** [comment]
Can we add to the replace color block description to indicate the proper replacement distance value when connecting in a gradiant on https://doc.babylonjs.com/divingDeeper/materials/node_material/nodeMaterial#list-of-available-blocks. @Popov72 - Do you have any guidance on this?

**Comment by Popov72** [comment]
I'm not sure to understand what is the relation between this block and a gradiant?

I think however that the description is misleading, there's no blending of colors: the output color is `replacement` if the distance between `value` and `reference` is less than distance, else it is `value`. I have created a PR in the doc and main repo to update the description.

**Comment by PirateJC** [comment]
It looks like this was largely taken care of already, but I added an example NME snippet that shows how to use the node. That should help future people see it working to understand it further.

https://nme.babylonjs.com/#98NGSE

https://github.com/BabylonJS/Documentation/pull/403
