### ISSUE TITLE
Add what import are needed for each class

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Documentation#158]
@thomlucc commented on [Tue Feb 18 2020](https://github.com/BabylonJS/OldDocumentationSite/issues/1887)

A game developer used typescript to port a game, and sometimes found it difficult to locate what imports he needed to access a certain class - having this listed clearly in the docs for each class would be really useful.

**Comment by PirateJC** [comment]
This is technically already available. 

You can find the information here:
https://doc.babylonjs.com/divingDeeper/developWithBjs/treeShaking#faq
