### ISSUE TITLE
Hard to locate items in the left menu

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#16]
![image](https://user-images.githubusercontent.com/4152247/98739148-2872f600-23a9-11eb-9eea-44164af4d04f.png)
It's not easy to clearly see where each item starts/ends.

Maybe we can add a bullet (or something else) in front of the items:
![image](https://user-images.githubusercontent.com/4152247/98739322-68d27400-23a9-11eb-9f06-6ad3ca9705f3.png)
(from Unity doc)

**Comment by RaananW** [comment]
A bullet will make a lot of sense. thanks!
