### ISSUE TITLE
Wrong playground link in documentation - Chapter 6 - Particle Spray

### ISSUE THREAD

**Issue by kihonkai** [BabylonJS/Documentation#167]
on the page: https://doc.babylonjs.com/start/chap6/particlespray
Getting Started - Chapter 6 - Particle Spray

the second playground link is titled: Add the Spray
It links to: https://playground.babylonjs.com/#TC31NV#4

While the first playground link is titled: A Basic Particle Fountain
and links to: https://playground.babylonjs.com/#TC31NV#4

The second link appears to exist here: https://playground.babylonjs.com/#TC31NV#5

**Comment by kihonkai** [comment]
Does it seem like the titles might be wrong too?  The first one fits the page before (https://doc.babylonjs.com/start/chap6/fountain) and the second fits the next page (https://doc.babylonjs.com/start/chap6/onoff).

**Comment by PirateJC** [comment]
This has all been fixed now. 

Thanks so much for flagging this @kihonkai
