### ISSUE TITLE
Chapter 3 - Explain maths of creating the curve

### ISSUE THREAD

**Issue by LukeTOBrien** [BabylonJS/Documentation#168]
Hello,

You have code in [Chapter 3](https://doc.babylonjs.com/start/chap3/polycar) that creates the `Vector3`s for the curved front of the car:

```js
//curved front
for (let i = 0; i < 20; i++) {
    outline.push(new BABYLON.Vector3(0.2 * Math.cos(i * Math.PI / 40), 0, 0.2 * Math.sin(i * Math.PI / 40) - 0.1));
}
```

I think it would be useful as a aside (collapsable `div`?) if you explained the maths.  
Why loop until 20? Why divde by 40? etc.

Some people might like to encapsulate the code into a function, so they would need to know what the variables are.

Just a thought.

**Comment by PirateJC** [comment]
I'll pass this one over to @BabylonJSGuide to get his thoughts on it.

**Comment by thomlucc** [comment]
Thanks for the suggestion! We are trying to keep the starting guide as simple as possible and not introducing HTML or more advanced concepts and focusing on Babylon.js math.
