### ISSUE TITLE
Explain earcut in Chapter 3/Links to API ref and other pages.

### ISSUE THREAD

**Issue by LukeTOBrien** [BabylonJS/Documentation#169]
Me again.

Whilst following your [tutorial Chapter 3](https://doc.babylonjs.com/start/chap3/polycar) on my own file system I get the error `earcut is not defined`.  
I had a look in your documentation and I found [Polygon Mesh Builder](https://doc.babylonjs.com/divingDeeper/mesh/creation/param/polyMeshBuilder) says:  

> Whilst an Earcut script is pre-loaded in the Playground you will have to add a reference to such a script in your own projects. One is available at cdn or via a npm package.

I think a lot of beginers will do the same as I did, work through the code on their own file systems using the playground as a ref and will get the same error as me.  
I would recomend mentioning about earcut in Chapter 3 as an aside and also link to the other documentation page.

---

I also think that you could add links to you API refference in general - Whenever we encounter a new part of the Babylon API, bold highligh and link it.

**Comment by thomlucc** [comment]
Hi @LukeTOBrien, thanks for flagging this. Would you be willing to submit a small PR about it?

**Comment by LukeTOBrien** [comment]
I would be willing to have a try, I can explain how I found out about it myself

**Comment by LukeTOBrien** [comment]
I've created a PR https://github.com/BabylonJS/Documentation/pull/286
