### ISSUE TITLE
Adding GUI with billboardMode = all

### ISSUE THREAD

**Issue by JPeer264** [BabylonJS/Documentation#197]
I raised [a ticket](https://forum.babylonjs.com/t/advanceddynamictexture-createformesh-rotate-with-camera/19421) yesterday in the forum. The answer is indeed nice, and not part of the [GUI documentation](https://doc.babylonjs.com/divingDeeper/gui/gui)

If this is a great case for the documentation, I would add it into the docs (would be a great addition to the second example `Texture MODE`. Here is the playground offered in the comments https://playground.babylonjs.com/#ZI9AK7#1214

**Comment by RaananW** [comment]
@msDestiny14 - want to take care of that?

**Comment by msDestiny14** [comment]
Adding to the docs sure! :)

**Comment by msDestiny14** [comment]
This is merged can now close :)
