### ISSUE TITLE
Blender Exporter Install is missing a few steps

### ISSUE THREAD

**Issue by JakeLaCombe** [BabylonJS/Documentation#199]
While doing the blender export, I notice there was a few extra steps to get the exporter installed according to this issue (https://github.com/BabylonJS/BlenderExporter/issues/20). Essentially, it's not the zip file from github you install. You download the zip file, unzip it, and within the unzipped folder, there is an additional zip folder. That's the one to install.

Would it be worth adding these steps to the documentation?

**Comment by RaananW** [comment]
It will be great if you can share your experience! We will be happy to merge it :-)

**Comment by thomlucc** [comment]
Hi @JakeLaCombe - Can you elaborate on what issues you had and better yet submit a PR with the modifications you'd like to see?

**Comment by JakeLaCombe** [comment]
Sure!

So it's something that is very small, but I think it can be confusing. On the first line of the installation instructions here (https://doc.babylonjs.com/extensions/Exporters/Blender#installation), it says that you don't need to unzip the folder, but what I had to do was unzip the code at https://github.com/BabylonJS/BlenderExporter, and inside that file there is another file you need to install. I feel it could potentially confusing that the guide says you don't need to unzip, but you first unzip the repository, and then take the zipped file that is exported and install that one. I've included a screenshot of the folder if it makes more sense.

![Babylon](https://user-images.githubusercontent.com/2552573/122624160-90d33580-d064-11eb-86d8-170fa2dbdb33.png)

If you don't think the installation instruction needs to be too deep, I'm fine with that. If you think this tidbit could help, I'd be happy to submit a PR.

**Comment by thomlucc** [comment]
Thanks for the detailed explanation. If you were confused, probably others will be so it would be great if you can submit a PR.

**Comment by Palmer-JC** [comment]
If you are going to change, you might just have them click on the zip
file.  It brings up a page with a download button.  That will get the zip
file to use.  The user has no need to either download or fork the repo
itself.
[image: zip file.JPG]

**Comment by Palmer-JC** [comment]
Sorry I replied by mail.  I guess picture do not go through.

![zip file](https://user-images.githubusercontent.com/7916131/122782816-0581bc00-d27f-11eb-8a7c-fefc085048d5.JPG)

**Comment by JakeLaCombe** [comment]
Thank you! That's what confused me! When I saw the zip part, I was thinking
it meant download the entire repo as a zip and import it, not the
individual file in the root file.

For me, I maybe would have said in the first step "Download the
Blender2Babylon-xxx.zip found in the root directory", but this was just my
experience installing this tool.

**Comment by RaananW** [comment]
Want to submit a fix for that page?

**Comment by PirateJC** [comment]
Addressed in this PR: https://github.com/BabylonJS/Documentation/pull/663
