### ISSUE TITLE
Headers should be half big as they are

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Documentation#2]
![image](https://user-images.githubusercontent.com/1306056/98732357-e4093b00-2353-11eb-8bfe-59a7032ebd3f.png)

**Comment by deltakosh** [comment]
More like that:

![image](https://user-images.githubusercontent.com/1306056/98738988-6ba77780-235d-11eb-8c26-598f89b4dd7e.png)

**Comment by Popov72** [comment]
What about simply removing this title? You already have it on the left menu + on the navigation bar at the top:
![image](https://user-images.githubusercontent.com/4152247/98742284-750d0000-23ae-11eb-8255-aec7c4c2389c.png)
We would save quite some space by removing it completely.

**Comment by deltakosh** [comment]
I kind of like that idea!

**Comment by RaananW** [comment]
Will hurt the page ranking, as there will be no h1 tag stating where the document starts. I don't want the title as well, it is simply something the search engines are still looking for.

I'll reduce the sizes of all h-tags

**Comment by Popov72** [comment]
Can't you make a CSS that makes the title invisible? I think the search engines will still find the h1 tag?

**Comment by RaananW** [comment]
Nope, those kind of hacks easily detected and rather punished :-) Besides, we need to think about other devices (like mobiles).

Headers size reduced
