### ISSUE TITLE
Links in tutorial pages are to old azure site

### ISSUE THREAD

**Issue by MrMormon** [BabylonJS/Documentation#2]
Of course, the playground links are fine as they are, but you can't go to the next tutorial in a series by using the link at the bottom of the previous one.

I've never done a pull request before. Is this something I should work on manually or is there an easier fix?

**Comment by Temechon** [comment]
Hi McMormon, 
The documentation is not finished yet, and this point still need to be resolved (but we are currently working on it :) )
No need to be a PR for this, we will take care of this soon.
Anyway, thank you for your report!
