### ISSUE TITLE
Add the ability to create notifications in docs

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Documentation#207]
For example a warning that a feature is not available in XR or that a certain function is deprecated.
This will require a new markdown element that can be added to doc pages.

**Comment by impurity-dev** [comment]
@RaananW What exactly did you have in mind for this? Would it be on the entire page?

**Comment by RaananW** [comment]
The idea is to have some form of a markdown element that lets you add notes and remarks. Something similar to alerts in material design (https://mui.com/material-ui/react-alert/)

**Comment by impurity-dev** [comment]
@RaananW can this be closed?
