### ISSUE TITLE
Broken links + misc

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#22]
I tried to perform a thorough review of all the pages, clicking on all possible links (I have certainly missed some)!

I stopped at Diving Deeper -> Materials (not included) if someone wants to take over!

* https://new-doc-page.vercel.app/start/chap1/first_scene
  * not broken, but all the links in the first paragraph points to this page, don't know if it's expected
* https://new-doc-page.vercel.app/start/chap1/first_viewer
  * "Viewer" => links to the same page
  * "Example Web Page" => 404
* https://new-doc-page.vercel.app/start/chap1/first_app
  * "First App" => 404
  * "First Coded App" => 404
* https://new-doc-page.vercel.app/start/chap2/placement
  * "position" => links to the same page
  * "rotation" => 404
* https://new-doc-page.vercel.app/start/chap2/viewer2
  * "Example Viewer - Village" (2 occurrences) => 404
* https://new-doc-page.vercel.app/start/chap2/app2
  * "Example App and Instructions" (2 occurrences) => 404
* https://new-doc-page.vercel.app/start/chap3/parent
  * text "LINK TO PARENTS" is not a link
* https://new-doc-page.vercel.app/start/chap3/import_character
  * animated gif of dude deformed
* https://new-doc-page.vercel.app/divingDeeper/animation/animation_introduction
  * deformed picture of the horse
* https://new-doc-page.vercel.app/divingDeeper/animation/groupAnimations
  * "creating an animation" => 404
* https://new-doc-page.vercel.app/divingDeeper/animation/animatedCharacter
  * "ImportMesh" => points to the old doc site
  * "Action Manager" => 404
  * "Device Source Manager" => 404
  * "animation blending" => 404
* https://new-doc-page.vercel.app/divingDeeper/animation/advanced_animations
  * https://www.babylonjs-playground.com/#IQN716#9 is not handled as a PG sample
  * "Scene API documentation" => points to the old doc site
  * "Animatable" => points to the old doc site
  * "AnimationGroups" => points to the old doc site
  * "AnimationGroup" => points to the old doc site
  * "Skeleton" => points to the old doc site
  * "Animation" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/cameras/camera_introduction
  * "Gamepad" (2 occurrences) => 404
  * "Virtual Joysticks David Rousset Blog" => 404
  * "Using the WebVR Camera" => 404 -> also, there's an extra ";"
* https://new-doc-page.vercel.app/divingDeeper/cameras/multiViewsPart1
  * "WebGL Multiview extension" => 404
* https://new-doc-page.vercel.app/divingDeeper/cameras/layerMasksAndMultiCam
  * the text in the left menu reads "Layermasks and Multi-Cam Textures" => missing a space between Layer and masks
* https://new-doc-page.vercel.app/divingDeeper/cameras/webVRCamera
  * "WebXR camera" => points to the old doc site
  * "introduction to WebXR" => points to the old doc site
  * "WebVR Experience Helper" => 404
* https://new-doc-page.vercel.app/divingDeeper/cameras/webVRHelper
  * "WebXR experience helper" => points to the old doc site
  * "introduction to WebXR" => points to the old doc site
  * "Multiview" => 404
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/forum
  * "documentation" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/npmSupport
  * "NPM_Support" => maybe "NPM Support" instead?
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/npmSupport#installing-other-babylon-modules
  * "the ES6 documentation" => points to the old doc site-> also, there's an extra ";"
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/howToStart
  * "here" => 404-> also, there's an extra ";"
  * "What's New" => points to the old doc site
  * http://localhost:1338/sandbox/index-local.html should be http://localhost:1338/sandbox/public/index-local.html
  * Inspector: http://localhost:1338/inspector/index.html => should we keep this link?
  * "the formatting of comments for the API" => 404
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/approvedNamingConventions
  * "documentation" => points to the old doc repo
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/usingThePlaygroundForBJSDev
  * https://github.com/BabylonJS/Babylon.js/blob/master/src/Math/babylon.math.ts => 404
  * "how to start contributing" => 404
  * "Code Guidelines" => points to the old doc site
  * "Comments in the API" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/contributeToDocs
  * https://github.com/BabylonJS/Documentation/tree/master/content => points to the old doc repo
  * "Documentation" => points to the old doc repo
  * "Documentation/public/html/img/" => points to the old doc repo
  * "Adding new images" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/environment/environment_introduction
  * "here" => 404
  * "scene helpers" => 404
* https://new-doc-page.vercel.app/divingDeeper/environment/skybox
  * "library textures in the playground" => 404
* https://new-doc-page.vercel.app/divingDeeper/environment/backgroundMaterial
  * "Environment documentation" => 404
* https://new-doc-page.vercel.app/divingDeeper/environment/lenseFlare
  * broken picture for "Lens flares"
* https://new-doc-page.vercel.app/divingDeeper/environment/360VideoDome
  * "VideoTexture" => 404
* https://new-doc-page.vercel.app/divingDeeper/events/actions
  * https://www.babylonjs-playground.com/#9RUHH#5 is not handled as a PG sample
* https://new-doc-page.vercel.app/divingDeeper/events/observables
  * "GUI", "scene.onPointerObservable" => 404
  * "Observable", "Observer", "API" => point to the old doc site
  * all links under "Observable Methods and Properties" point to the old doc site
  * "Observable.add" => point to the old doc site
  * all links under "Scene Observables" point to the old doc site
  * "Interactions HowTo" => 404
* https://new-doc-page.vercel.app/divingDeeper/events/interactWithScenes
  * "GUI" => 404
* https://new-doc-page.vercel.app/divingDeeper/gui
  * "CastorGUI", "documentation" => 404
  * "dat.GUI" => wrong link
* https://new-doc-page.vercel.app/divingDeeper/gui/gui
  * "3D GUI system" => points to the old doc site
  * https://doc.babylonjs.com/features/playground_debuglayer#gui-control-actions => points to the old doc site
  * "here" (for ScrollViewer) => 404
  * "Turning AdaptToDeviceRatio Off/On" => 404
* https://new-doc-page.vercel.app/divingDeeper/gui/selector
  * Fig 1 has no picture / text
* https://new-doc-page.vercel.app/divingDeeper/gui/gui3D
  * "behaviors" => points to the old doc site
  * "2D GUI content" => points to the old doc site
  * when clicking on "Babylon 3D GUI" in the left menu, the "The Babylon GUI" entry gets also selected
* https://new-doc-page.vercel.app/divingDeeper/input/deviceSourceManager
  * "DeviceSourceManager" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/importers/loadingFileTypes
  * all 3 links under "Basic Usage" => 404
  * "How to Use Promises" => 404
  * "Load Files with Assets Manager" => 404
* https://new-doc-page.vercel.app/divingDeeper/importers/glTF
  * "Load from any file type" => 404
  * "properties and methods" => points to the old doc site
  * "extensions" => points to the old doc site
* https://new-doc-page.vercel.app/divingDeeper/importers/stl
  * https://github.com/BabylonJS/Babylon.js/tree/master/dist/preview => 404
  * "how to load from any file type" => 404
* https://new-doc-page.vercel.app/divingDeeper/importers/oBJ  
  * https://github.com/BabylonJS/Babylon.js/tree/master/dist/preview => 404
  * "NPM support" => 404
  * "how to load from any file type" => 404
* https://new-doc-page.vercel.app/divingDeeper/importers/assetManager
  * "warning" => 404
  * picture in the "Using a loading screen" section has a broken link
* https://new-doc-page.vercel.app/divingDeeper/importers/assetContainers
  * "loading from files" => 404
* https://new-doc-page.vercel.app/divingDeeper/lights/shadows
  * https://playground.babylonjs.com/#B48X7G is not handled as a PG sample
  * "dedicated page" => 404
* https://new-doc-page.vercel.app/divingDeeper/lights/shadows_csm
  * "Shadows" => 404
  * the links 2 and 3 at the bottom of the page are not displayed correctly

**Comment by PirateJC** [comment]
All links and images fixed! Thanks so much for the thorough list @Popov72 You rock!
