### ISSUE TITLE
Contribution guide outdated

### ISSUE THREAD

**Issue by wilcoschoneveld** [BabylonJS/Documentation#220]
Hello!

I just recently got involved with BabylonJS and I would like to contribute. However, when initializing and building the repository locally I get a whole lot of file changes which clogs up my entire git tree. 

In the official guide ([here](https://doc.babylonjs.com/divingDeeper/developWithBjs/howToStart#the-build)) it's stated that one should `git update-index --assume-unchanged` a bunch of files, however not all files are stated since I have 103 file changes when I build fresh from master.

I found two related issues on the forum which are not solved;
https://forum.babylonjs.com/t/gitignore-dist-bad-convention/6679
https://forum.babylonjs.com/t/git-update-index-assume-unchanged/7934

What is the daily workflows that the main contributors are using?

Additionally, are there more resources that I can look at to learn more about the repository structure?

I would like to contribute to improving the documentation on this. Thanks a lot!

To write about:
- [ ] Ignoring preview release changes
- [ ] Line endings git config
- [ ] How to contribute on a mac
- [ ] ...

**Comment by RaananW** [comment]
Hey, Thanks a lot for the willing to help! 
The forum would be the right place to talk about it, but i totally agree, the guide is outdated. 
There is no need for weird git commands. All you need to do is fork, fetch, merge, branch, commit, submit a PR 😎. Reading this makes me wonder why i think it's simple...

Want to discuss this on the forum? This way the rest of the team will be able to contribute to the discussion as well.

**Comment by wilcoschoneveld** [comment]
Thanks @RaananW, I started a topic on the forum here: https://forum.babylonjs.com/t/what-is-the-best-workflow-for-contributing-to-babylonjs/20463
