### ISSUE TITLE
Missing Images at start of page

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Documentation#231]
@RaananW  Similar to closed issue #117

Ref https://doc.babylonjs.com/guidedLearning/workshop/Geodesic_Math first three images not showing up. Had this problem when working locally with this page, except that on some occasions they did appear.  Hoped it would not happen after the PR.

**Comment by thomlucc** [comment]
Looks like it is fixed. Please re-open if needed.
