### ISSUE TITLE
BoundingInfo - explain the different types of strategies

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Documentation#232]
main issue here - https://doc.babylonjs.com/typedoc/classes/babylon.boundinginfo#isinfrustum . We should explain what each strategy does, or at least link to the right place in code.

**Comment by sebavan** [comment]
One part is here : https://github.com/BabylonJS/Babylon.js/pull/13249/files#diff-6a01f545e7ce0a4282f8c7529e06b8e1659c754bebdcf2a78deda9534658d07aR186 and the other one in PR in a sec
