### ISSUE TITLE
Add examples for NME (in the PG examples)

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Documentation#262]

**Comment by RaananW** [comment]
The documentation page supports NME. It does display the entire screen though, as there is no preview (frame)  mode

**Comment by deltakosh** [comment]
I meant examples for the playground page here:
![image](https://user-images.githubusercontent.com/1306056/122242816-776d9600-ce78-11eb-973a-0b92431b6c0b.png)

I did several demos and each time I want to showcase NodeMaterial loading I need to dig into the doc

**Comment by RaananW** [comment]
Oh, awesome. So it's only adding the category and marking a few.

**Comment by PirateJC** [comment]
https://github.com/BabylonJS/Documentation/pull/266
