### ISSUE TITLE
Scroll bar not restored when navigating

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Documentation#3]
so if you go there https://new-doc-page.vercel.app/advanced_topics/introToShaders
and then scroll down and click on Using ShaderMaterial the scroll bar does not go back to top
(the new page is loaded bu the scroll bar stays at the bottom)

**Comment by RaananW** [comment]
should be fine now, please check and close if it's working correctly

**Comment by deltakosh** [comment]
All good!
