### ISSUE TITLE
Texture Canvas examples do not work in 5.0

### ISSUE THREAD

**Issue by andreasplesch** [BabylonJS/Documentation#315]
https://doc.babylonjs.com/extensions/textureCanvas links to two Playground examples which do not seem to work in 5.0.0 but do work in 4.2.0 , for me (Chrome, webgl2, linux).

So this may be more of a TextureCanvas extension [issue](https://github.com/BabylonJS/Extensions/issues/227) than a documentation issue. But for now the documentation could link to a 4.2.0 playground (if possible) to avoid confusion.

**Comment by sebavan** [comment]
I ping @poolminer there as he is the maintainer for the TextureCanvas so lets see if he is available to help :-)

cc @RaananW and @PirateJC for the follow up.

**Comment by PirateJC** [comment]
Since Texture Canvas is a community supported feature, until it is updated to work with 5.0, I'll add a note in the doc that makes it clear that the feature should be used with 4.2 and below.

**Comment by PirateJC** [comment]
Addressed in this PR: https://github.com/BabylonJS/Documentation/pull/663
