### ISSUE TITLE
Remove all mentions of deprecated functions in code samples

### ISSUE THREAD

**Issue by RaananW** [BabylonJS/Documentation#359]
Any mention of deprecated functions (like Mesh.Create???) should be replaced with the new function.

**Comment by RaananW** [comment]
List of playground to process:

https://playground.babylonjs.com/#JA1ND3#6
https://playground.babylonjs.com/#FH3FM2#4
https://playground.babylonjs.com/#8GY6J8#198
https://playground.babylonjs.com/#N96NXC
https://playground.babylonjs.com/#JA1ND3#63
https://playground.babylonjs.com/#X6MQ1L
https://playground.babylonjs.com/#RA18GJ
https://playground.babylonjs.com/#ZT8BKT#2
https://playground.babylonjs.com/#7QCYPB
https://playground.babylonjs.com/#9CLJEF
https://playground.babylonjs.com/#YAWBMY
https://playground.babylonjs.com/#TAFSN0#230
https://playground.babylonjs.com/#5MV04
https://playground.babylonjs.com/#YPABS1
https://playground.babylonjs.com/#G9VPHQ
https://playground.babylonjs.com/#TAFSN0#323
https://playground.babylonjs.com/#LG3GS#107
https://playground.babylonjs.com/#JA1ND3#40
https://playground.babylonjs.com/#JA1ND3#18
https://playground.babylonjs.com/#SRV2A0
https://playground.babylonjs.com/#RC2IAH#1
https://playground.babylonjs.com/#DGEP8N
https://playground.babylonjs.com/#M7MYT8#11
https://playground.babylonjs.com/#VIGXA3#7
https://playground.babylonjs.com/#PCY1J#4
https://playground.babylonjs.com/#KST50Y
https://playground.babylonjs.com/#76U9TK
https://playground.babylonjs.com/#DEYAQ5#47
https://playground.babylonjs.com/#8L50Q3#1
https://playground.babylonjs.com/#1CL0BO
https://playground.babylonjs.com/#5G9MC5
https://playground.babylonjs.com/#FH3FM2#5
https://playground.babylonjs.com/#GG06BQ#97
https://playground.babylonjs.com/#K41IJ
https://playground.babylonjs.com/#G3Q7GR#1
https://playground.babylonjs.com/#24C4KC#17
https://playground.babylonjs.com/#8GY6J8#199
https://playground.babylonjs.com/#5A4TP5
https://playground.babylonjs.com/#VS5XS7#0
https://playground.babylonjs.com/#C21DGD#2
https://playground.babylonjs.com/#PPM311#63
https://playground.babylonjs.com/#ZHYP5K
https://playground.babylonjs.com/#FH3FM2#10
https://playground.babylonjs.com/#JA1ND3#48
https://playground.babylonjs.com/#ULACCM#2
https://playground.babylonjs.com/#1H7L5C#37
https://playground.babylonjs.com/#5Y2GIC#39
https://playground.babylonjs.com/#KJ8ZRZ#2
https://playground.babylonjs.com/#YCCU8U
https://playground.babylonjs.com/#3B5W22#29
https://playground.babylonjs.com/#FAXLY2
https://playground.babylonjs.com/#7HH1UH

**Comment by BabylonJSGuide** [comment]
Still to be updated

https://playground.babylonjs.com/#JA1ND3#6
https://playground.babylonjs.com/#8GY6J8#198
https://playground.babylonjs.com/#JA1ND3#63
https://playground.babylonjs.com/#X6MQ1L
https://playground.babylonjs.com/#RA18GJ
https://playground.babylonjs.com/#7QCYPB
https://playground.babylonjs.com/#9CLJEF
https://playground.babylonjs.com/#YAWBMY
https://playground.babylonjs.com/#TAFSN0#230
https://playground.babylonjs.com/#5MV04
https://playground.babylonjs.com/#G9VPHQ
https://playground.babylonjs.com/#TAFSN0#323
https://playground.babylonjs.com/#JA1ND3#40
https://playground.babylonjs.com/#JA1ND3#18
https://playground.babylonjs.com/#SRV2A0
https://playground.babylonjs.com/#DGEP8N
https://playground.babylonjs.com/#M7MYT8#11
https://playground.babylonjs.com/#VIGXA3#7
https://playground.babylonjs.com/#KST50Y
https://playground.babylonjs.com/#76U9TK
https://playground.babylonjs.com/#DEYAQ5#47
https://playground.babylonjs.com/#5G9MC5
https://playground.babylonjs.com/#GG06BQ#97
https://playground.babylonjs.com/#G3Q7GR#1
https://playground.babylonjs.com/#8GY6J8#199
https://playground.babylonjs.com/#5A4TP5
https://playground.babylonjs.com/#C21DGD#2
https://playground.babylonjs.com/#ZHYP5K
https://playground.babylonjs.com/#JA1ND3#48
https://playground.babylonjs.com/#5Y2GIC#39
https://playground.babylonjs.com/#KJ8ZRZ#2
https://playground.babylonjs.com/#YCCU8U
https://playground.babylonjs.com/#3B5W22#29
https://playground.babylonjs.com/#FAXLY2
