### ISSUE TITLE
Video tutorials are broken

### ISSUE THREAD

**Issue by 1-800-jono** [BabylonJS/Documentation#414]
Seems the video tutorials located at: https://doc.babylonjs.com/guidedLearning/videos are down. Checked in FF and Chrome.

**Comment by PirateJC** [comment]
Thanks for flagging this!

It looks like the hosting service for the videos in that section of the docs decided to remove the content.

It's actually ok though. That content was pretty old and outdated so it was probably time to remove it. 

I've captured a new issue to tackle this in the new year.

https://github.com/BabylonJS/Documentation/issues/416
