### ISSUE TITLE
Add YouTube Videos to Guided Learning Section

### ISSUE THREAD

**Issue by PirateJC** [BabylonJS/Documentation#416]
The old tutorial videos were removed by the hosting service. 

It's time to replace them with more recent content.

https://github.com/BabylonJS/Documentation/issues/414

**Comment by impurity-dev** [comment]
@PirateJC What content did you have in mind for this? Do you just want links added [here](https://doc.babylonjs.com/guidedLearning/videos) to the YT videos the babylon team created? Or is this more community created content?

**Comment by PirateJC** [comment]
@impurity-dev, definitely open to brainstorm here. In general it's creating video content that could exist in both the YouTube and in the docs. Both community created content as well as stuff from the dev team would be great!

We could easily start with links to existing content on YouTube, but then expand that with whatever we think would be helpful to the community!
