### ISSUE TITLE
Add section on service worker caching 

### ISSUE THREAD

**Issue by carolhmj** [BabylonJS/Documentation#417]
Looking at this issue: https://forum.babylonjs.com/t/gltf-file-cache-not-updating/12656, I think it could be interesting to have a section on the caching page: https://doc.babylonjs.com/divingDeeper/scene/optimizeCached dedicated to service workers. Seems like they are the recommended solution for caching file-based content, in which our models would fall into: https://web.dev/storage-for-the-web/.

**Comment by PirateJC** [comment]
@carolhmj - Is this still relevant? Something we should still consider doing?

**Comment by KennyStanleyJr** [comment]
I think so 🤓 @PirateJC

**Comment by thomlucc** [comment]
Closing as it is not Babylon specific but more pure javascript
