### ISSUE TITLE
"Fix" PG search results design

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Documentation#43]

**Comment by RaananW** [comment]
Initial change implemented:

![image](https://user-images.githubusercontent.com/1381702/99534207-565aca80-29a7-11eb-856e-15585d3f49d7.png)

It is possible to open the playground inline and to open it externally. You can also click on the tokens (tags) to search for other playgrouns with the same tags.

**Comment by deltakosh** [comment]
Far better :D
