### ISSUE TITLE
Something wrong on the page of Materials and Vertices

### ISSUE THREAD

**Issue by sknightq** [BabylonJS/Documentation#479]
On the page of Materials and Vertices, I think something wrong with the [content](https://doc.babylonjs.com/divingDeeper/materials/advanced/facet_uvs#issues-with-adjoining-faces).

> For example if the image above was to be wrapped around faces 3, 2, 6, 7 and 1, 2, 6, 5 and 0, 1, 5, 4 and 0, 3, 7, 4 it is not possible for vertex 3 to be assigned (1, 0) and (1, 1) nor for vertex 7 to be assigned (0, 0) and (1,0).

I think the content should be: **vertex 3 to be vertex 3 to be assigned (0, 1) and (1, 1)**

**Comment by RaananW** [comment]
I am pretty sure the sentence is correct, but I will be happy to be proven wrong. vertex3 cannot be assigned both of those values. It is being assign 0,1, as written in the section before - https://doc.babylonjs.com/divingDeeper/materials/advanced/facet_uvs#textures-at-vertices

**Comment by sknightq** [comment]
@RaananW I mean that the coordinate of UV(texture) is wrong, the vertex 3 is mapped to (0,1) or (1,1) as the following image.
![Screenshot from 2022-03-07 12-01-59](https://user-images.githubusercontent.com/8033144/156965827-154fb05f-c2b6-4a0b-b47d-c468eb314c9d.png)

**Comment by PirateJC** [comment]
Adding @PatrickRyanMS to get his thoughts on this.

**Comment by PatrickRyanMS** [comment]
@sknightq, the documentation is correct that a vertex cannot be assigned two UV coordinates at once. Using your image as an example, you have laid out the UV coordinates for the cube, but in this case, the vertex labeled as `3` and `7` in the cube is actually a split vertex and is actually two vertices. This always happens along UV seams. So what your diagram should look like is:

![image](https://user-images.githubusercontent.com/31326855/192592986-035c01d0-710a-48c9-9f9b-c0d354440a62.png)

This is why the vertex count of a mesh can change based on how it is UVed. I hope this makes sense.

**Comment by PirateJC** [comment]
Thanks @PatrickRyanMS
