### ISSUE TITLE
Documentation for v5 BABYLON.GridMaterial not up to date

### ISSUE THREAD

**Issue by Myrmod** [BabylonJS/Documentation#501]
I wanted to use the `BABYLON.GridMaterial` from https://doc.babylonjs.com/toolsAndResources/assetLibraries/materialsLibrary/gridMat#using-the-grid-material, however the links are broken.

I can create a pull request if I find the required file , if that's ok with you.

**Comment by sebavan** [comment]
I think they are all removed from the repo following the latest changes. They should probably point at our CDN. cc @RaananW to confirm ?

**Comment by rpaladin** [comment]
@Myrmod in case you didn't were able to find the mentioned migrated scripts, here's a link to the CDNs:

Developer version: https://cdn.babylonjs.com/materialsLibrary/babylon.gridMaterial.js
Release version: https://cdn.babylonjs.com/materialsLibrary/babylon.gridMaterial.min.js

**Comment by RaananW** [comment]
I was pretty sure I went over all links to the dist folder, but it seems like some are still there! Sorry about that.

as @rpaladin wrote, the CDN holds those files. Our repository no longer stores them.

I am keeping this open. Will close this once all links are removed.

**Comment by Myrmod** [comment]
I understand, thank you. I will give them a try
