### ISSUE TITLE
Broken links under "Playground" section

### ISSUE THREAD

**Issue by rpaladin** [BabylonJS/Documentation#534]
Webpage reference: https://doc.babylonjs.com/divingDeeper/developWithBjs/frameworkVers

![image](https://user-images.githubusercontent.com/69180012/164370293-afe96148-0789-4b7e-b929-5c11713adc53.png)

## Issue 1
Highlighted `Typescript` links through incompatible/missing Typescript functions - strangely the other demo links all work fine in Typescript, whether initially or on api toggle.

## Issue  2
`"some html templates"` link raises 404.

## Issue 3
`index-local.html` link raises 404.

## Issue 4
15 image links are broken.

**Comment by RaananW** [comment]
Page reference - https://doc.babylonjs.com/toolsAndResources/tools/playground

**Comment by RaananW** [comment]
updated, closing issue.
