### ISSUE TITLE
info missing from lights_introduction page

### ISSUE THREAD

**Issue by OptiStrat** [BabylonJS/Documentation#544]
Some info seems to be missing in [this section](https://doc.babylonjs.com/divingDeeper/lights/lights_introduction#lighting-normals) of the doc. (At least a picture the text refers to.)

**Comment by RaananW** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/1381702/165941046-4d5ccffc-b7cd-4785-93ff-faf261ef0f5c.png)

Do you see something different?

**Comment by OptiStrat** [comment]
Hmm... I didn't think the browser would have an impact on this... Clearly I was wrong.
Under Fedora 35, I see what you see in Chrome 100.0.4896.88, but in FireFox 99.0 this is what I see:

![image](https://user-images.githubusercontent.com/62603084/165944124-504d4cbf-5601-4399-8ebf-b773605e9978.png)

**Comment by OptiStrat** [comment]
That seems to be happening on any documentation page with some images in it, actually.

**Comment by RaananW** [comment]
The firefox was solved, but I see it's back there. I'll check that, thanks!

**Comment by RaananW** [comment]
Ok, this seems to be an issue with firefox itself (and its decode mechanism):

https://bugzilla.mozilla.org/show_bug.cgi?id=1758035

the size is reported to be 1, 1 (which is what we are getting as well), instead of the right size. i'll see what we can do in the meantime

**Comment by OptiStrat** [comment]
Thank you @RaananW for looking into this.
Apparently this stems from a 'bug' in the HTML spec, but hopefully the Mozilla team will fix their implementation soon. It'd be sad to have to switch to Chrome for casual browsing on Linux boxes...

**Comment by RaananW** [comment]
I find it to be a shame that we don't support firefox. I will probably remove the next image support for the time being

**Comment by RaananW** [comment]
This was resolved.
