### ISSUE TITLE
Example of Packer with download need to be update

### ISSUE THREAD

**Issue by ziiip** [BabylonJS/Documentation#577]
There is a typo error in playground named "Texture Packer Download Example" (https://playground.babylonjs.com/#TQ408M#7), which is linked with https://github.com/BabylonJS/Documentation/blob/master/content/How_To/material/Creating_a_Texture_Package.md

"pack.downoad('jpeg', 0.325);" should be "pack.download('jpeg', 0.325);", the `l` is missing.

**Comment by RaananW** [comment]
Thanks, I submitted a fix, it will be in in 10-15 minutes.
