### ISSUE TITLE
child node not follow parent, when i rotation the parent

### ISSUE THREAD

**Issue by lence-wl** [BabylonJS/Documentation#586]
In chap3/animation, when i export in playground , then i use " BABYLON.SceneLoader.ImportMeshAsync " import, child node not follow parent, when i rotation the [parent]

**Comment by RaananW** [comment]
@PirateJC - can you look into that?

**Comment by PirateJC** [comment]
Hi @lence-wl Can you provide us with any more information? What specific step are you following in the documentation?

Is it this page: https://doc.babylonjs.com/start/chap3/animation

Are you you referring to this playground: https://playground.babylonjs.com/#KDPAQ9#15

Where you import the car and apply animations to the wheels? 

How are you exporting your models from the playground?

Thank you in advance for the more information!

**Comment by PirateJC** [comment]
Closing for now due to lack of response. Further clarity needed before taking action.
