### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#59]
I reviewed everything but "Guided Learning" and "Extensions".

* https://doc.babylonjs.com/divingDeeper/developWithBjs/howToStart
  * http://localhost:1338/sandbox/index-local.html should be http://localhost:1338/sandbox/public/index-local.html
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/approvedNamingConventions
  * "documentation" => points to the old doc repo
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/usingThePlaygroundForBJSDev
  * https://github.com/BabylonJS/Babylon.js/blob/master/src/Math/babylon.math.ts => 404
* https://new-doc-page.vercel.app/divingDeeper/developWithBjs/contributeToDocs
  * https://github.com/BabylonJS/Documentation/tree/master/content => points to the old doc repo
  * "Documentation" => points to the old doc repo
  * "Documentation/public/html/img/" => points to the old doc repo
* https://new-doc-page.vercel.app/divingDeeper/gui
  * "dat.GUI" => wrong link
* https://new-doc-page.vercel.app/divingDeeper/gui/selector
  * Fig 1 has no picture / text
* https://new-doc-page.vercel.app/divingDeeper/gui/gui3D
  * when clicking on "Babylon 3D GUI" in the left menu, the "The Babylon GUI" entry gets also selected
* https://new-doc-page.vercel.app/divingDeeper/importers/stl
  * "how to load from any file type" => 404
* https://new-doc-page.vercel.app/divingDeeper/lights/shadows_csm
  * the links 2 and 3 at the bottom of the page are not displayed correctly => only the text should be visible and behave like a link
* https://doc.babylonjs.com/divingDeeper/materials/using/introToPBR
  * "Ashkimin Shirley Microfacets" => 404
* https://doc.babylonjs.com/divingDeeper/materials/using/ktx2Compression
  * "Working with compressed texture formats" paragraph => bad layout of the text + link not as a link
* https://doc.babylonjs.com/divingDeeper/materials/advanced/logarithmicDepthBuffer
  * http://www.gamasutra.com/blogs/BranoKemen/20090812/85207/Logarithmic_Depth_Buffer.php => broken
* https://doc.babylonjs.com/divingDeeper/mesh/creation/set/tiled_plane
  * "This image..." => there's no image displayed
* https://doc.babylonjs.com/divingDeeper/mesh/creation/param/ribbon_extra
  * when clicking on "Ribbon in Detail" in the left menu, "Ribbon" entry gets also selected
* https://doc.babylonjs.com/divingDeeper/mesh/creation/param/ribbon_maths
  * when clicking on "Ribbon with Maths" in the left menu, "Ribbon" entry gets also selected
* https://doc.babylonjs.com/divingDeeper/mesh/transforms/parent_pivot/pivots
  * when clicking on "Pivots" in the left menu, "Rotate Around Axis" entry gets also selected
* https://doc.babylonjs.com/divingDeeper/mesh/decals
  * link to "Decal" picture broken
* https://doc.babylonjs.com/divingDeeper/postProcesses/usePostProcesses
  * "this" in "Read this if you want to know how to fix it." => 404
* https://doc.babylonjs.com/divingDeeper/scene/optimizeOctrees
  * https://www.babylonjs.com/?OCTREE does not link to the right page
  * https://www.babylonjs.com/?INSTANCES does not link to the right page
* https://doc.babylonjs.com/divingDeeper/scene/renderToPNG
  * text too big for the "hint:" paragraph
* Sprites => Sprite Map
  * maybe make a sub-directory below Sprite Map to put all the sprite map related pages?
* https://doc.babylonjs.com/divingDeeper/tags
  * two broken picture links
* https://doc.babylonjs.com/divingDeeper/webXR/webXRInputControllerSupport
  * "WebXR Input Source" => 404
* https://doc.babylonjs.com/advanced_topics/introToShaders/shaderCodeInBjs
  * "BABYLON.ShaderMaterial" => 404
* https://doc.babylonjs.com/toolsAndResources/tools/playground
  * "indexStable.html" => produces errors in the console log
* https://doc.babylonjs.com/toolsAndResources/tools/inspector
  * "Introduction to the inspector - video series" => 404
* https://doc.babylonjs.com/toolsAndResources/tools/inspector/customizingInspector
  * "How to Start Contributing to Babylon.js" => 404
  * "this tutorial" => 404
  * "here" in "here in Github" => 404
* https://doc.babylonjs.com/toolsAndResources/tools/particleEditor
  * "The Inspector" => 404
* https://doc.babylonjs.com/toolsAndResources/tools/spriteEditor
  * "The Inspector" => 404
* https://doc.babylonjs.com/toolsAndResources/tools/skeletonViewer
  * "The Inspector" => 404
  * "Skeleton Viewer Documentation" => 404
* First 4 pages + "Shadow Only" + "Cell Shading" below Tools and Resources => Available Asset Libraries => The Materials Library
  * links not displayed as links / 404
* https://doc.babylonjs.com/toolsAndResources/assetLibraries/materialsLibrary/skyMat
  * "A Practical Analytic Model for Daylight" and "Simon Wallner" => 404
* https://doc.babylonjs.com/toolsAndResources/assetLibraries/postProcessLibrary/asciiArtPP
  * https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview => 404
  * https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview => 404
* https://doc.babylonjs.com/toolsAndResources/assetLibraries/postProcessLibrary/digitalRainPP
  * https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview => 404
  * https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview => 404
* https://doc.babylonjs.com/toolsAndResources/utilities/Minimise_Vertices
  * "Materials and Facets" => 404
* https://doc.babylonjs.com/toolsAndResources/offsite
  * "PR in Github" => points to the old doc repo

Also:
* bad layout when multiple PGs:
  * eg: https://doc.babylonjs.com/divingDeeper/mesh/creation/param/custom_extrude
![image](https://user-images.githubusercontent.com/4152247/98986088-b7f0e400-2524-11eb-97a8-a9ee9f66e687.png)
* legend beneath a picture is too far below
    eg: https://doc.babylonjs.com/divingDeeper/mesh/transforms/parent_pivot/pivots
![image](https://user-images.githubusercontent.com/4152247/98986935-d73c4100-2525-11eb-8402-8383deb89b0e.png)
* small display problem when showing code in a bullet point list (https://doc.babylonjs.com/divingDeeper/particles/solid_particle_system/sps_vertices)
![image](https://user-images.githubusercontent.com/4152247/98988479-06ec4880-2528-11eb-9caa-1349bc173aa7.png)

**Comment by RaananW** [comment]
Image alignment is now correct,
Text code blocks now have a top margin to separate between them. I leave the rest to @PirateJC  :-)

**Comment by PirateJC** [comment]
Fixed all links apart from these:

https://www.babylonjs.com/?OCTREE from https://doc.babylonjs.com/divingDeeper/scene/optimizeOctrees
https://www.babylonjs.com/?INSTANCES from https://doc.babylonjs.com/divingDeeper/scene/optimizeOctrees
https://www.babylonjs-playground.com/indexStable.html#6F0LKI#2 from https://doc.babylonjs.com/toolsAndResources/tools/playground

**Comment by PirateJC** [comment]
Fixed Octree doc demos.

Leaving indexStable as is for now.
