### ISSUE TITLE
Please add Details about Rotation

### ISSUE THREAD

**Issue by ghost** [BabylonJS/Documentation#597]
Please add Details to this article https://doc.babylonjs.com/divingDeeper/mesh/transforms/center_origin/rotation and mention the scale being used. I just wanted to hack something together quickly and id have liked to find information about how much i need to rotate to effectively rotate 90°. Theres no information about the units being used to rotate on the page.

**Comment by PirateJC** [comment]
@ThetaEdra, if you have specific improvements or additions you'd like to see added, we'd gladly welcome a PR from you to improve this doc! Any interest?

**Comment by PirateJC** [comment]
@ThetaEdra if you have specific additional information you think would be helpful, please let me know, otherwise I'll close out this issue. Thanks!

**Comment by ghost** [comment]
Like i said specific Information that would be helpful are for example what the unit scale for rotation and other operations is. For example how can a Plane or any other entity be rotate for 90°. See Unitys Documentation for example Descriptions: https://docs.unity3d.com/ScriptReference/Quaternion.html

I think https://doc.babylonjs.com/features/featuresDeepDive/mesh/transforms/center_origin/rotation never mentions once what kind of unit is to be supplied to the orientation operation (Degree, Numeric Value, ...).

Its just rather disappointing not to have such basic Information documented. I used this Framework for a small Project where it was necessary to use but i dont plan on using it ever again. Also i lack the knowledge to extend the documentation properly. For those two reasons its highly unlikely that i will contribute any concrete PRs or spcific Informations.

It just feels like the Documentation is not enough to build solid Projects and get a solid i idea of whats going on when some basic Information that other Frameworks provide is missing. Easiest way is to just compare the Documentation to other Frameworks that use a proper Documentation.

**Comment by BabylonJSGuide** [comment]
@PirateJC are you happy to close this PR?
