### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by arcman7** [BabylonJS/Documentation#615]
---
title: Mesh Picking
image:
description: Learn how to pick meshes in Babylon.js.
keywords: diving deeper, meshes, interactions
further-reading:
    - title: Mesh Overview
      url: /divingDeeper/mesh/creation/set
    - title: Forum Pick with Ray
      url: https://www.html5gamedevs.com/topic/26503-scenepickwithray-blues/
    - title: Forum World Local Ray
      url: https://www.html5gamedevs.com/topic/26602-worldlocalray/
    - title: Forum Gobal to Local
      url: https://www.html5gamedevs.com/topic/7599-convert-global-coordinates-to-local-coordinates/
video-overview:
video-content:
---

All of the html5gamedevs.com links do not work.

**Comment by RaananW** [comment]
@PirateJC - we need to remove all of the html5gamedevs links, as they are all offline

**Comment by PirateJC** [comment]
This is being addressed with the following PR:

https://github.com/BabylonJS/Documentation/pull/622
