### ISSUE TITLE
Misc issues (2)

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#62]
I have finished checking all the pages of the doc repo, here are my findings.

* https://doc.babylonjs.com/guidedLearning/createAGame/musicSFX
  * "Playing Sounds and Music" => 404
* https://doc.babylonjs.com/guidedLearning/createAGame/closing
  * "here" from "You can check out the game here" => 404
* https://doc.babylonjs.com/guidedLearning/videos/videoCourses
  * "Agenda" => broken picture link + all 8 links below are 404
* https://doc.babylonjs.com/guidedLearning/workshop/Car_Driven
  * "Simple Car" => 404
* https://doc.babylonjs.com/guidedLearning/workshop/House_Use
  * "development of this code" => 404
* https://doc.babylonjs.com/guidedLearning/workshop/roof
  * "design" and "coding" => 404
  * PG "Example Roof Floor" and "Example Roof" not displayed correctly as a PG
* https://doc.babylonjs.com/guidedLearning/workshop/Track
  * PG "Example - A Short Track" and "Example - Closed Track" and "Example - Open Track" and "Example - Velodrome" not displayed correctly as a PG
  * PG "Example - Overview of Roller Coaster" and "Example - Passenger View from Roller Coaster" not displayed correctly as a PG
* https://doc.babylonjs.com/guidedLearning/workshop/Issues
  * "Simple Particle Collisions on a Grid" => 404
  * "Slow Particles" => 404
* https://doc.babylonjs.com/guidedLearning/workshop/Slow_Collide
  * "issues" => 404
* https://doc.babylonjs.com/guidedLearning/workshop/Free_Collide
  * "issues" and "slow particles" and "Slow Particles" => 404
* https://doc.babylonjs.com/guidedLearning/workshop/vr_game
  * "here" in "A more in depth guide can be found here." => 404
* https://doc.babylonjs.com/guidedLearning/workshop/Writing2
  * the screenshot of the PG is an empty picture (all blue)
* https://doc.babylonjs.com/extensions/babylonViewer/viewerTemplatingSystem
  * "Template class." => 404
* https://doc.babylonjs.com/extensions/babylonViewer/defaultViewerConfig
  * https://handlebarsjs.com/reference.html => 404
* https://doc.babylonjs.com/extensions/castorGUI
  * "Demo online of this extension" => site does not respond
  * "Documentation" => does not link to Castor doc
  * PGs don't work because the actifgames.com does not respond
* https://doc.babylonjs.com/extensions/dynamicTerrains
  * a PG link not displayed correctly after the sentence: "A Dynamic Terrain generated without any data map looks like a simple planar ribbon initially"
* https://doc.babylonjs.com/extensions/dynamicTerrains/addingDTObjects
  * missing title for the last 2 PGs
* https://doc.babylonjs.com/extensions/dynamicTerrains/DTExamples
  * the last PG link of the page is not displayed correctly
* https://doc.babylonjs.com/extensions/meshWriter
  * first PG, link in the page is "https://www.babylonjs-playground.com/#PL752W#1" but when clicking on icon it is https://playground.babylonjs.com/#E6OZX#221 (which has nothing to do with mesh writer)
  * https://www.babylonjs-playground.com/#PL752W#1 does not work because of "Failed to load resource: net::ERR_CERT_DATE_INVALID" (error in console)
* https://doc.babylonjs.com/extensions/textureCanvas
  * extra texts "<<<<<<< HEAD" and ">>>>>>> 0a9d2fb9c99e3447ee3122c8df9d8182db9c7827" (2 times in the page)
* https://doc.babylonjs.com/extensions/treeGenerators/quickTreeGenerator
  * http://www.pixelcodr.com/tutos/trees/trees.html => 404
* https://doc.babylonjs.com/extensions/Editor/Explaining_Workflow
  * "here" in "You can also see a demo of the underlying material PBR Material type here." => 404
  * "Resources" in "There's a bunch of articles on this in the Resources section of the BabylonJs Docs." => 404
* https://doc.babylonjs.com/extensions/Editor/Using_Photoshop_Extension
  * http://blogs.adobe.com/photoshop/2013/09/introducing-adobe-generator-for-photoshop-cc.html => site archived
* https://doc.babylonjs.com/extensions/Exporters/3DSMax_to_glTF
  * https://github.com/KhronosGroup/glTF/pull/1223)[KHR_lights_punctual => 404
* https://doc.babylonjs.com/extensions/Exporters/3Dtext
  * "3D Text site" => 404
* https://doc.babylonjs.com/extensions/Exporters/Blender
  * "Tower of Babel" => 404
  * "QueuedInterpolation" => 404
  * "tip" in "useful when using ArcRotate camera (tip)" => 404
  * "tip" in "Arc Rotate (tip)" => 404
  * "tip" in "Use an edge split modifier instead, see tip." => 404
  * "Materials" in "about automatic baking, see Materials." => 404
  * "tip" in "See tip for a basic workflow." => 404
  * ".zip archive" => 404
* https://doc.babylonjs.com/extensions/Exporters/Bones_influences_per_vertex
  * "bones influences parameter En" picture link broken
* https://doc.babylonjs.com/extensions/Babylon.js+ExternalLibraries/BabylonJS_and_Instant_Games
  * "Facebook Dashboard" => blank page
* https://doc.babylonjs.com/extensions/Unity/02_SceneManager
  * "TypeScript Definitions" => 404
* https://doc.babylonjs.com/extensions/Unity/05_TerrainBuilder
  * "Terrain Editing" => picture link broken
* https://doc.babylonjs.com/extensions/Unity/07_RuntimePrefabs
  * "Prefab Override" => picture link broken

**Comment by PirateJC** [comment]
Have done a pass through all of these. All fixed (or removed if outdated)
