### ISSUE TITLE
Broken link on Getting Started page

### ISSUE THREAD

**Issue by gmlewis** [BabylonJS/Documentation#677]
On this page: https://doc.babylonjs.com/features/introductionToFeatures/chap1/first_viewer
the "Example Web Page" link is broken here:
https://github.com/BabylonJS/Documentation/blame/master/content/features/introductionToFeatures/chap1/first_viewer.md#L29

It looks like the "public/webpages" folder might need to be moved under the "content" folder in order for it to be found.

**Comment by gmlewis** [comment]
Same thing for this page: https://doc.babylonjs.com/features/introductionToFeatures/chap1/first_app
and the "First Coded App" link.

Basically, anything that starts with "/webpages".

**Comment by RaananW** [comment]
@PirateJC - do you ahve time for this?
