### ISSUE TITLE
When PGs are displayed on a page the text for the ‘Coming Next’ sections get lost

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/Documentation#678]
For example 

https://doc.babylonjs.com/features/featuresDeepDive/crowdNavigation

**Comment by RaananW** [comment]
I can't reproduce:

![image](https://user-images.githubusercontent.com/1381702/196406771-3ec02af8-48b1-4ae3-8225-0420775dac52.png)

Or maybe I misunderstood the issue?

**Comment by BabylonJSGuide** [comment]
@RaananW  seems to be a Firefox and Chrome Issue. Edge does two per row

![image](https://user-images.githubusercontent.com/19671146/196624745-1b6d91de-f0fd-4ec8-88b4-de8df7cd0889.png)

Did a screen resolution check of my value range laptop - mine was set at 1920 x 1080 with a scale factor of 150%, changing to 125% overcomes the issue but makes everything more difficult to read. 

So more my problem than yours

**Comment by RaananW** [comment]
Needs to be addressed then 😊
I'll check that
