### ISSUE TITLE
Controls block thumbnail broken

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Documentation#72]
The Babylon.js logo on the controls block under the Diving Deeper coming next is shifted from center and is wrapping strangely.

![image](https://user-images.githubusercontent.com/31326855/99439874-9dbf5900-28ca-11eb-91f4-473c83fde6e7.png)

**Comment by RaananW** [comment]
This is actually working as intended. The default image of each article is the first image found in it. The page had an image: https://doc.babylonjs.com/divingDeeper/controls

This can be overridden in the page's metadata. @PirateJC , want to update the image for the controls page?

**Comment by PatrickRyanMS** [comment]
Makes sense. Given the format of the image on the block, we may need to be diligent about passing images that make sense when viewed in this block if the first image does not lend itself well.

**Comment by PirateJC** [comment]
Needed in the image filter control preview box as well

![image](https://user-images.githubusercontent.com/1668182/122799767-f991fc00-d276-11eb-9616-68fb77cafc0d.png)

**Comment by PirateJC** [comment]
Talked to @RaananW - Looks like the metadata image property isn't being updated properly?

When setting the image property to the default image the coming next images still appear broken.

**Comment by RaananW** [comment]
the metatdata key should be `image-url` instead of `image`

**Comment by PirateJC** [comment]
You sir, are a GENIUS!

fixed!

https://github.com/BabylonJS/Documentation/pull/395

Note - Currently all doc pages have metadata currently using the 'image' property. We MIGHT want to consider doing a batch operation to fix them all? Thoughts?
