### ISSUE TITLE
ToC formatting update for legibility

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Documentation#73]
To help legibility on the table of contents links, we should align the chevron with the first line of links that wrap lines and make the chapter part of the title bold. This will help the reader distinguish where the lines end and be able to distinguish the topics of chapters that line wrap:

![image](https://user-images.githubusercontent.com/31326855/99443635-f1807100-28cf-11eb-96af-f87ba3bf6d56.png)

_Note that the bullet under chapter 1 was aligned with the first line of a wrapping title as well._ 
 
If we want to avoid bolding in the table of contents other than the active link to help with contrast, I would suggest dropping the word "Chapter" and just leading with the number. The repetition of the word chapter surrounding the first word of the second line is what is causing the eye to want to pick up a pattern and have trouble reading the second line. The bold adds contrast to allow the second line to stand out. Removing the word chapter would have the same effect since every line would be different.

**Comment by RaananW** [comment]
I like the idea of removing "chapter". Will leave the decision to @PirateJC . 

About the chevron and the bullet point - will be done tomorrow 😁

**Comment by PirateJC** [comment]
Fixed:

https://github.com/BabylonJS/Documentation/pull/396
