### ISSUE TITLE
Multiple documentation pages mention Gulp, but it's no longer used

### ISSUE THREAD

**Issue by phildremi** [BabylonJS/Documentation#770]
I just returned from a wild goose chase trying to find out where it's used, and from what I can tell it isn't appearing anywhere. Also:

* The [Tools/Publisher](https://github.com/BabylonJS/Babylon.js/tree/99ea1b5f4bee52fed8e61136cf6c717e5159da1a/Tools/Publisher) directory mentioned doesn't exist anymore, but `git blame` didn't help me find out what happened to it
* The docs claim that [What's New](https://doc.babylonjs.com/whats-new) will inform about newer Gulp versions. It did not :)
* Changes to the build system were mentioned only once, for 3.0 (and not 5.0, which I assume was when this may have changed)
* The actual contribution guide doesn't involve Gulp at all, so something's definitely off (unless it's used "behind the scenes"?)

Anyway, I didn't know if I should just remove mention from the docs or if it's actually still required.

My FOSS time ran out before I could finish the investigation, so I'll leave this here and check back later.

**Comment by RaananW** [comment]
These are old relics from an older version of the build system. We will be happy to take care of that if you point where you see it

**Comment by phildremi** [comment]
I can send a PR with the fixes later. Just wanted to make sure it's no longer used before I remove anything of value ;)

**Comment by RaananW** [comment]
There are certain changes we will be happy to do ourselves, but we will be happy to see your suggested changes

**Comment by impurity-dev** [comment]
https://github.com/search?q=repo%3ABabylonJS%2FDocumentation%20gulp&type=code

A naïve search found some Gulp references in the documentation. Most seem to be contribute docs

**Comment by RaananW** [comment]
still an open issue. there are, for sure, outdated doc pages. We are slowly updating these docs. If we have a list of docs that must be updated ASAF - that would be very helpful :-) 
this link shows a few files that MUST be updated, that's for sure

**Comment by phildremi** [comment]
Sorry, completely forgot about this. I mostly just searched for "gulp" in the docs. So if those pages are fixed that'll be the bulk of it.

Edit: IIRC, there were also references in various READMEs of the [engine repo](https://github.com/BabylonJS/Babylon.js).

**Comment by RaananW** [comment]
#1067
