### ISSUE TITLE
Colyseus demos broken - Caused by suspended server

### ISSUE THREAD

**Issue by rpaladin** [BabylonJS/Documentation#787]
Reference: https://doc.babylonjs.com/guidedLearning/networking/Colyseus
All demos that use [Glitch](https://glitch.me) as the server host are broken because the Glitch servers have been suspended it seems.

![image](https://user-images.githubusercontent.com/69180012/222927869-df9cb44f-0db9-4f6e-9a5c-cd0650be82cf.png)

This may be due to the fact that Glitch enforces very strict restrictions on their free accounts, which is realistically understandable. More details on these restrictions here: https://glitch.happyfox.com/kb/article/17-technical-restrictions/#Container%20Space

**Comment by RaananW** [comment]
Was added in this PR:

https://github.com/BabylonJS/Documentation/pull/475

Will ping @endel just in case, otherwise we will have to work on a solution.

**Comment by endel** [comment]
Hi guys, I'm contacting the Glitch team trying to get the app unsuspended - this happened sometime last year but they managed to unsuspend it. 

I wanna migrate this demo away from Glitch to avoid possible future suspensions. Hope they can fix this on their end in the meantime. Will let you know asap! 🙏

**Comment by endel** [comment]
The app has been unsuspended by the Glitch team 🙏

**Comment by PatrickRyanMS** [comment]
Confirmed the example is up and running again. Thanks for your help, @endel!
