### ISSUE TITLE
Keep layout for API doc

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#83]
We should keep the carriage returns / global layout of the API doc as is, else it makes reading more difficult.

For eg:
![image](https://user-images.githubusercontent.com/4152247/99853634-a68e8400-2b83-11eb-8afd-4336573aefaa.png)

Whereas in the source code it is:
![image](https://user-images.githubusercontent.com/4152247/99853663-b27a4600-2b83-11eb-8728-e044febb8cf8.png)

**Comment by RaananW** [comment]
I am now using pre-white spaces on the text, so it should be fine.
