### ISSUE TITLE
Force redirect prevents back navigations from working

### ISSUE THREAD

**Issue by FreakTheMighty** [BabylonJS/Documentation#856]
I've noticed a few times that Babylonjs docs sometimes prevent me from leaving. It gives a spammy website vibe, but I suspect its just a bug.

* Google https://doc.babylonjs.com/typedoc/classes/BABYLON.VideoTexture
* Navigate to BABYLON.VideoTexture through the link (this give you a browser history)
* Click anywhere on the page
* Try to use the back button

Notice that the page refuses to go back to the search page.

I'm using Chrome 113.0.5672 on a Mac.

**Comment by RaananW** [comment]
hash values are a part of the URL history. so when you go back it goes back to the last hash (or no hash).
Not spammy website vibes, i hope, but the right behavior :-)

**Comment by FreakTheMighty** [comment]
@RaananW I get that anchors should be recorded in history but I'm seeing something being added to history even though I'm not clicking on an anchor and no matter how many times I click back, I can't get leave the page (that's the spammy website vibe).

https://github.com/BabylonJS/Documentation/assets/247092/e9686a15-828d-477f-99c0-5bb7ab6015e5

**Comment by RaananW** [comment]
oh! I see. I think I know what causes this. 
I can't reproduce this on the browser I am using (both edge and chrome on windows), but i think i know the code that might cause this. Thanks!

**Comment by RaananW** [comment]
Fix is being deployed and will be available shortly. Thanks again!

**Comment by FreakTheMighty** [comment]
Thank you! Much better :)
