### ISSUE TITLE
Using <Youtube id="xxx"/> causes Hydration errors. 

### ISSUE THREAD

**Issue by jamessimo** [BabylonJS/Documentation#862]
I am updating a community extension page with my own video and added the video ID in the YAML header and inline using the <Youtube> tag and I get these errors. 

<img width="285" alt="Screen Shot 2023-05-22 at 13 00 21" src="https://github.com/BabylonJS/Documentation/assets/4888377/f6a3673b-9811-42a2-b445-300a1407bfb8">

<img width="967" alt="Screen Shot 2023-05-22 at 12 59 15" 
src="https://github.com/BabylonJS/Documentation/assets/4888377/0f07c470-4a00-4382-8cce-7364e532ab43">

I can dismiss the errors and the videos do show on the page and can be played. Not sure if I need to inform the page to expect the youtube video?  I used other videos from the docs and get the same issue. 

```
Error: Hydration failed because the initial UI does not match what was rendered on the server.

```

**Comment by RaananW** [comment]
Probably something new that was added in next 13. I'll investigate. thanks a lot for letting me know!

**Comment by thomlucc** [comment]
PR to be merged
