### ISSUE TITLE
API reference shows twice in the result

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Documentation#871]
Search for `loadScript` in the documentation, the API reference comes up twice.

[Search results: loadScript | Babylon.js Documentation (babylonjs.com)](https://doc.babylonjs.com/search?q=loadScript)

![image](https://github.com/BabylonJS/Documentation/assets/19158740/f6605ebd-ec37-4bfa-961d-72b9e3f1fec9)

First one is: https://doc.babylonjs.com/typedoc/classes/babylon.tools

Second one is: https://doc.babylonjs.com/typedoc/classes/BABYLON.Tools

**Comment by RaananW** [comment]
Search index cleared (problem resolved). Will close this issue when I implement a solution as part of the CI.
